name: Build and Push Docker Image

on:
    push:
        branches: [main, master]
        tags: ["v*"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DEFAULT_TAG: "latest"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push multi-arch image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      type=raw,value=${{ env.DEFAULT_TAG }}
                      type=raw,value={{date 'YYYYMMDD'}}
                      type=raw,value=${{ env.DEFAULT_TAG }}.{{date 'YYYYMMDD'}}
                      type=sha,enable=${{ github.event_name == 'pull_request' }}
                      type=ref,event=pr
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
